version: "3.8"

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-graph
    ports:
      - "7474:7474" # Browser UI
      - "7687:7687" # Bolt protocol
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: apoc
    volumes:
      - neo4j_data:/var/lib/neo4j/data
      - neo4j_logs:/var/lib/neo4j/logs

volumes:
  neo4j_data:
  neo4j_logs:
