@rem Central configuration for batch scripts
set "DEFAULT_PROJ_ROOT=C:\Users\jfhar\OneDrive\Desktop\github\graph_tutorials"
set "ECHO_SERVER_PATH=%DEFAULT_PROJ_ROOT%\src\api_test\echo_server.py"
set "ECHO_SERVER2_PATH=%DEFAULT_PROJ_ROOT%\src\api_test\echo_server2.py"
set "GRAPHQL_PATH=%DEFAULT_PROJ_ROOT%\src\api_test\graphql_test.py"
set "ECHO_PORT1=6001"
set "ECHO_PORT2=6002"
set "GRAPHQL_PORT=6003"
set "A_NAME=lcmg"
set "A_BRANCH=mp"
set "LCMG_REPO=https://github.com/jfharney77/lcmg.git"
